### ISSUE TITLE
Set up dedicated domain and deploy the site there (2h)

### ISSUE THREAD

**Issue by freemvmt** [fac18/safe-space#116]
- [x] Advise MU on how to direct traffic from their domains to the Netlify deploy
- [x] Configure Netlify account appropriately
- [x] Force redirects from .co.uk to .org.uk

**Comment by edificex** [comment]
Finished except that redirects from .co.uk to .org.uk don't seem to work (despite appearing in toml).

**Comment by edificex** [comment]
Despite adding a _redirects file which ends up in the site folder, and double checking syntax against Netlify docs, this still isn't working !!

**Comment by edificex** [comment]
Made a [post](https://community.netlify.com/t/domain-level-redirects-failing-despite-being-processed-without-errors/11632) on Netlify community forum - waiting for any helpful responses.

**Comment by freemvmt** [comment]
**RESOLVED**

This was a proper saga, and as with all things in software dev, the solution was frustratingly simple. We simply had the lines in the _redirects file in the wrong order. Moving `/* /index.html 200` to the bottom immediately sorted the domain redirect problem.

Unfortunately this _didn't_ fix the 404 sidestep i.e. invalid URLs were not being automatically served with the /index.html, but I resolved this by building a proper Error404 component out of the already existing Error500, and adding it as a final catch to the React Router Switch.

cf. PRs #178, #179, #180, #181, #182, #183, #184
