### ISSUE TITLE
Make other more minor changes (16h)

### ISSUE THREAD

**Issue by edificex** [fac18/safe-space#120]
- [ ] Make error pages for different cases (404 and 500) - DG
- [ ] Make FAQ questions collapsible (or else have an anchored list) - RH or DG
- [x] Make logo click through to Home throughout app (but warn user before leaving report) - RH
- [x] Change logo for section dividers for WCAG compliant contrast - RH
- [ ] Add link to FAQs with more info on the user reference - RH
- [x] Make footer stick to bottom on all pages - RH
- [x] Edit logo to use just the ‘MU’ part of the logo w/o ‘Musicians’ Union’ text - RH
- [x] Make logo consistent throughout app - RH
- [ ] Make sure logo sticks to top of each page - RH
- [x] Make links clickable on Support cards - RH
- [x] Bigger/wider text entry fields – especially for the long form response at ‘/report/3’ - RH
- [ ] Add sharing options to About page and link to this from final page after reporting - RH
- [x] Make sure the copy in About page reflects document from client - RH
- [x] Introduce validation for email field - DG
- [x] Scan for and attend to instances of 'BUG' and 'NEED TO' in codebase comments

**Comment by redahaq** [comment]
I've  made separate issues for the changes still outstanding and moved this into Done. Hope that's cool!
