### ISSUE TITLE
Handle failure of airtable fetch (i.e. status 500)

### ISSUE THREAD

**Issue by redahaq** [fac18/safe-space#155]
And serve them at the appropriate times!

(see comments for clarifications)

**Comment by edificex** [comment]
Actual 404s (i.e. attempts to navigate to pages not served) should be handled by Netlify redirects back to the SPA, as per issue #116. 500s are most likely failures with the lambdas/Airtable connection, so should show a component asking the user to refresh the page (e.g. by clicking a button that runs something like `window.location.reload(true)`)
