### ISSUE TITLE
Final bugs!

### ISSUE THREAD

**Issue by freemvmt** [fac18/safe-space#174]
- [x] scroll bars appearing on desktop for some users (but fine in Report, so it could be a result of Header or Footer component)
- [x] secondary button text invisible on safari (mobile and desktop)
- [x] primary/secondary buttons stack out of alignment for small screens
- [x] width of smaller text on Home page (i.e. too wide)

**Comment by redahaq** [comment]
I haven't managed to recreate the stacking out of alignment issue @edificex . Are you able to?
